name: meta_corpus_stats_generator

on:
  workflow_dispatch:

jobs:
  meta_corpus_stats_generator:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
          submodules: recursive
          token: ${{ secrets.MS3_BOT_TOKEN }}
      - name: Configure git and push updated workflow
        working-directory: ./main
        continue-on-error: true
        run: |
          git config --global user.name "ms3-bot"
          git config --global user.email dcml.annotators@epfl.ch
          git config --global user.token ${{ secrets.MS3_BOT_TOKEN }}
          git add -A
          git commit -m "Current version of workflows"
          git push
      - name: Pull latest updates into submodules
        working-directory: ./main
        run: |
          git submodule foreach "git checkout -f main | git clean -f | git pull --no-rebase --allow-unrelated-histories origin main"
      - name: Pull current workflow
        working-directory: ./main
        run: |
          wget https://github.com/DCMLab/annotation_workflow_template/archive/refs/heads/meta_corpora.zip
          unzip meta_corpora.zip
          cp -r annotation_workflow_template-meta_corpora/. .
          rm -r annotation_workflow_template-meta_corpora/
          rm meta_corpora.zip
      - name: Clone ms3
        uses: actions/checkout@v2
        with:
          repository: johentsch/ms3
          ref: workflow
          path: ./ms3
      - name: Install ms3
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ./ms3
      - name: Run ms3 extract
        working-directory: ./main
        run: |
          ms3 extract -D
          ms3 extract -D
      - name: Push files
        working-directory: ./main
        continue-on-error: true
        run: |
          git add -A
          git commit -m "Automatically added TSV files from parse with ms3"
          git push
      - name: Clone corpusstats
        uses: actions/checkout@v2
        with:
          repository: DCMLab/corpus_statistics_generator
          path: ./corpusstats
          ref: main
          token: ${{ secrets.MS3_BOT_MAINTENANCE  }}
      - name: Install corpusstats
        run: python -m pip install -e ./corpusstats
      - name: Generate GitHub pages
        working-directory: ./main
        run: |
          python .github/workflows/update_pages.py -g ${{ github.repository }} -t ${{ secrets.MS3_BOT_MAINTENANCE  }} -o ../public
      - name: Display generated files
        working-directory: ./public
        run: ls
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true

